---
    - name: Deploy
      vars:
        url: "http://mirrors.jenkins.io/war-stable/latest/jenkins.war"
       # app: "cart"
      tasks:

      - name: Creating the dir
        file:
          path: /tmp/{{app}}/source
          state: directory

      - name: removing the content
        shell: rm -rf /tmp/{{app}}/source/*
        args:
          warn: false

      - name: Unarchiving the tar file
        unarchive:
          src: "{{ url }}"
          dest: /tmp/{{app}}/source
          remote_src: yes

          

